### PR TITLE
colorbar for heatmap

### PR DESCRIPTION
**Pull request by BioNinja**
* add colorbar below each heatmap
* rasterized image to reduce file size  when output vector graphic files

### CODE REVIEW

**Comment by BioNinja** [comment]
hi, @simonvh , I've create a PR to add colorbar, if you find colorbar is needed for heatmap. refer to #68

**Comment by simonvh** [comment]
Thanks for this! Looks good to me. However, it would indeed be necessary to make the colorbar optional. Can you make the colorbar code dependent on a flag/variable? Should be an argument of heatmap_plot, but can be set to True as default.

**Comment by BioNinja** [comment]
Add --no-colorbar option in the command line to turn off colorbar.

**Comment by simonvh** [comment]
Sorry, this took way too long. Thanks @BioNinja !

**Pull request merged**
